send_text:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: kapso_whatsapp
    to:
      example: "393331234567"
      required: true
      selector:
        text:
    message:
      example: The garage door is still open.
      required: true
      selector:
        text:
          multiline: true
    preview_url:
      default: false
      selector:
        boolean:

send_template:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: kapso_whatsapp
    to:
      example: "393331234567"
      required: true
      selector:
        text:
    template_name:
      example: ha_notification
      required: true
      selector:
        text:
    language:
      default: en_US
      example: en_US
      selector:
        text:
    body_parameters:
      example:
        - The garage door is still open.
      selector:
        object:

send_authentication_code:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: kapso_whatsapp
    to:
      example: "393331234567"
      required: true
      selector:
        text:
    template_name:
      example: auth_copy_code
      required: true
      selector:
        text:
    language:
      default: en_US
      example: en_US
      selector:
        text:
    code:
      example: "123456"
      required: true
      selector:
        text:
